### ISSUE TITLE
[Live Server] When character does /rc their health and stamina go to zero

### ISSUE THREAD

**Issue by Lantheos** [Lantheos/CalicoCountyDev#13]
┆Issue is synchronized with this [Trello card](https://trello.com/c/IKv9ULNq) by [Unito](https://www.unito.io)

**Comment by DarthVapers** [comment]
By design within the character script. We can't change it until it goes into LUA or we decompile/recompile it with the edits.

**Comment by Lantheos** [comment]
Fixed by Vorp_Character.
