### ISSUE TITLE
[Live-Server] Cart issues in Valentine

### ISSUE THREAD

**Issue by flamespinner** [Lantheos/CalicoCountyDev#24]
Support Ticket 88
RedM Crashes when a cart is spawned in Valentine stables (seems to do it when selecting a cart/when you have a cart pulled up in the stable store and spawn a cart you own). And spawns on the fence on the north side when in the menu. It has done it a few times to me now.

┆Issue is synchronized with this [Trello card](https://trello.com/c/RfLrngQs) by [Unito](https://www.unito.io)

**Comment by Lantheos** [comment]
Seems as if we don't have the camera positioning properly. We also need to look into adding the Town stable to Strawberry.

**Comment by DarthVapers** [comment]
Issue was fixed with recent stables update.
