### ISSUE TITLE
[Live Server] Add Bank to Armadillo

### ISSUE THREAD

**Issue by Lantheos** [Lantheos/CalicoCountyDev#28]
┆Issue is synchronized with this [Trello card](https://trello.com/c/jXQiNoiu) by [Unito](https://www.unito.io)

**Comment by Lantheos** [comment]
From Ticket 91 from @DarthVapers 

"The last time we attempted to alter the existing banks - we completely broke the entire banking system. Yes, we attempted to put a bank in Armadillo. It is on my list of "things to look into/do" but has to be done correctly as banking is a pretty important piece of the server. Doesn't mean I've written it off, just have to approach it differently than I did before 😉"

**Comment by Lantheos** [comment]
test

**Comment by DarthVapers** [comment]
Done on live server, works.
