### ISSUE TITLE
[Dev Server] Slow down Ranching Bubbles

### ISSUE THREAD

**Issue by Lantheos** [Lantheos/CalicoCountyDev#5]
Slowdown Ranching bubbles. Suspected Code line should be located at [RedM_dev/TxData/Vorpcore_77B133.Base/Resources/Syn Assets/Syn_Ranch/Html/index.js] at line 19-26.

**Comment by flamespinner** [comment]
Changed if statement starting on Line 22 of index.js of Syn_Ranch to a higher threshold than 3 milliseconds. Now if the random number generated is less than 7000 (7 seconds) it will automatically get set to 7000. @Lantheos tested this on his higher resolution monitor and it seems as if that had also changed the speed of the game slightly as well. This seems to have set the game at a more reasonable speed.

` 
    if (speed < 7000){
        return 7000
    }
}`

**Comment by flamespinner** [comment]
After some more testing, we have changed that 7000 to 4500. Seems to be about the sweet spot.
